app:
  storage-location: /Users/wangjinqiang/Download/temp
logging:
  level:
    root: info
    org.apache.coyote.http11.Http11InputBuffer: debug
spring:
  thymeleaf:
    cache: false

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///vpsTools?useSSL=false&characterEncoding=utf-8

  jpa:
    show-sql: true
